In [52]:
from os import sys
sys.path.append("/meshAfterParty")

In [ ]:
"""
11/24
Purpose: To follow Forrest's deom 'FrameworkDemo' from the tutorial

Note: currently 4x4x40 view
https://minnie.microns-daf.com/annotation/views/aligned_volume/minnie65_phase3
"""

In [1]:
from annotationframeworkclient import FrameworkClient
from IPython import html, display

/usr/local/lib/python3.6/dist-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

In [7]:
"""
How to reate a client without a datastack and then query what datastacks are available

"""
client = FrameworkClient()
client.info.get_datastacks()
#helps get info about datastack
client.info.get_datastack_info("minnie65_phase3_v1")

{'segmentation_source': 'graphene://https://minniev1.microns-daf.com/segmentation/table/minnie3_v1',
 'description': 'This is the first version of Minnie that has proofreading enabled. Was first enabled on June 24, 2020. ',
 'aligned_volume': {'id': 1,
  'description': "This is the second alignment of the IARPA 'minnie65' dataset, completed in the spring of 2020 that used the seamless approach.",
  'image_source': 'precomputed://https://seungdata.princeton.edu/minnie65-phase3-em/aligned/v1',
  'name': 'minnie65_phase3'},
 'analysis_database': None,
 'soma_table': 'nucleus_neuron_svm',
 'synapse_table': 'synapses_pni_2',
 'viewer_site': 'https://akhilesh-graphene-sharded-dot-neuromancer-seung-import.appspot.com/',
 'local_server': 'https://minnie.microns-daf.com'}

In [8]:
"""
The synapse table for this is "synapses_pni_2"
By specifying the datastack in the instantiation 
it will give all the information without having to specify it

- synapses_pni_1M was a test table and should be ignored

"""
client = FrameworkClient('minnie65_phase3_v1')

['my_new_table',
 'functional_coreg',
 'proofreading_functional_coreg_v2',
 'proofreading_functional_coreg',
 'allen_v1_column_types',
 'synapses_pni_1M',
 'synapses_pni_2',
 'nucleus_detection_v0',
 'nucleus_neuron_svm',
 'allen_v1_column_types_v2',
 'synapses_pni',
 'allen_v1_column_proofreading']

In [11]:
"""
How to see all of the tables available programatically

"""
print(client.annotation.get_tables())
#how to get the meta data for the table

#getting the metadata of the table 
ann_metadata = client.annotation.get_table_metadata(client.info.get_datastack_info()["synapse_table"])
ann_metadata

['my_new_table', 'functional_coreg', 'proofreading_functional_coreg_v2', 'proofreading_functional_coreg', 'allen_v1_column_types', 'synapses_pni_1M', 'synapses_pni_2', 'nucleus_detection_v0', 'nucleus_neuron_svm', 'allen_v1_column_types_v2', 'synapses_pni', 'allen_v1_column_proofreading']

{'schema_type': 'synapse',
 'valid': True,
 'created': '2020-11-04T06:48:36.953637',
 'user_id': 'foo@bar.com',
 'reference_table': None,
 'table_name': 'synapses_pni_2',
 'id': 36,
 'deleted': None,
 'description': 'Automated synapse detection performed by Nick Turner from the Seung Lab.  size represents the number of (4x4x40 nm) voxels painted by the automated cleft segmentation, and the IDs reference the IDs of the cleft segmentation.  Ctr_pt reflects the centroid of the cleft segmentation. The cleft segmentation volume is located in the flat_segmentation_source field. ',
 'flat_segmentation_source': None}

In [13]:
# getting the schema info (json format)
print(ann_metadata["schema_type"])
client.schema.schema_definition(ann_metadata["schema_type"])

synapse

{'$schema': 'http://json-schema.org/draft-07/schema#',
 'definitions': {'SpatialPoint': {'type': 'object',
   'required': ['position'],
   'properties': {'position': {'type': 'array'}},
   'additionalProperties': False},
  'BoundSpatialPoint': {'type': 'object',
   'required': ['position'],
   'properties': {'position': {'type': 'array'},
    'root_id': {'type': 'integer'},
    'supervoxel_id': {'type': 'integer'}},
   'additionalProperties': False},
  'SynapseSchema': {'type': 'object',
   'required': ['ctr_pt', 'post_pt', 'pre_pt'],
   'properties': {'ctr_pt': {'type': 'object',
     '$ref': '#/definitions/SpatialPoint',
     'description': 'a point located near/on the synaptic contact',
     'order': 1},
    'post_pt': {'type': 'object',
     '$ref': '#/definitions/BoundSpatialPoint',
     'description': 'a nearby point located in the postsynaptic compartment of the synapse',
     'order': 2},
    'pre_pt': {'type': 'object',
     '$ref': '#/definitions/BoundSpatialPoint',
     'description': 'a nearby point located in the presynaptic compartment of the synase',
     'order': 0},
    'size': {'title': 'size',
     'type': ['number', 'null'],
     'format': 'float',
     'description': 'size of synapse'},
    'valid': {'title': 'valid',
     'type': ['boolean', 'null'],
     'default': False,
     'description': 'is this annotation valid'}},
   'additionalProperties': True}},
 '$ref': '#/definitions/SynapseSchema'}

In [43]:
# specifying versions
print(f"Automatic version = {client.materialize.version}")
print(client.materialize.get_versions())

#how to se the version to whatever you want
client.materialize._version = 2
print(f"Automatic version = {client.materialize.version}")

Automatic version = 1
[1, 7, 2, 3]
Automatic version = 2

In [51]:
curr_version = 7
print(client.materialize.get_version_metadata(curr_version))
print(f"Moment of time everything is created = {client.materialize.get_version_metadata(curr_version)['time_stamp']}")

{'datastack': 'minnie65_phase3_v1', 'time_stamp': '2020-11-23T22:16:47.721975', 'id': 19, 'version': 7, 'valid': True}
Moment of time everything is created = 2020-11-23T22:16:47.721975

In [26]:
# get tables
client.materialize.get_tables()

['allen_v1_column_proofreading',
 'allen_v1_column_types_v2',
 'nucleus_detection_v0',
 'nucleus_neuron_svm',
 'proofreading_functional_coreg',
 'synapses_pni_2']

In [27]:
client.materialize.get_table_metadata("synapses_pni_2")

{'aligned_volume': 'minnie65_phase3',
 'valid': True,
 'created': '2020-11-17T00:45:41.193542',
 'schema': 'synapse',
 'table_name': 'synapses_pni_2',
 'analysisversion': 15,
 'id': 40}

# Ho to Get a Table

In [33]:
client.materialize.query_table?

Signature:
client.materialize.query_table(
    table:str,
    filter_in_dict=None,
    filter_out_dict=None,
    filter_equal_dict=None,
    filter_spatial=None,
    join_args=None,
    select_columns=None,
    offset:int=None,
    limit:int=None,
    datastack_name:str=None,
    materialization_version:int=None,
)
Docstring:
generic query on materialization tables

Args:
    table: 'str'

    filter_in_dict (dict , optional):
        keys are column names, values are allowed entries.
        Defaults to None.
    filter_out_dict (dict, optional):
        keys are column names, values are not allowed entries.
        Defaults to None.
    filter_equal_dict (dict, optional):
        inner layer: keys are column names, values are specified entry.
        Defaults to None.
    offset (int, optional): offset in query result
    limit (int, optional): maximum results to return (server will set upper limit, see get_server_config)
    select_columns (list of str, optional): columns to select. Defaults to None.
    suffixes: (list[str], optional): suffixes to use on duplicate columns
    offset (int, optional): result offset to use. Defaults to None.
        will only return top K results.
    datastack_name (str, optional): datastack to query.
        If None defaults to one specified in client.
    materialization_version (int, optional): version to query.
        If None defaults to one specified in client.
Returns:
pd.DataFrame: a pandas dataframe of results of query
File:      /usr/local/lib/python3.6/dist-packages/annotationframeworkclient/materializationengine.py
Type:      method

In [34]:
df = client.materialize.query_table('proofreading_functional_coreg',
                                    filter_in_dict=None,
                                    filter_out_dict=None,
                                    filter_equal_dict=None,
                                    filter_spatial=None,#not yet implemented
                                    select_columns,#reduces the amount of data you are pulling
                                   offset=None #this is an integer that will set the offset
                                   )

In [35]:
df.head()

,id,valid,pt_position,pt_supervoxel_id,pt_root_id,func_id
0,1,True,"[181147, 143788, 22167]",89660913577302088,864691135569117318,29020
1,2,True,"[182993, 135610, 21130]",89941288908184714,864691135517422218,61953
2,3,True,"[182993, 135610, 21130]",89941288908184714,864691135517422218,58941
3,4,True,"[149711, 151738, 17565]",85369450370657325,864691135724333739,28753
4,5,True,"[198949, 188854, 19772]",92129866602123648,864691135367058169,16062

In [39]:
"""
Example Query: Just specify the column and the value
"""
df = client.materialize.query_table('proofreading_functional_coreg',
                                    #filter_in_dict=dict(func_id=[58941,16062]),
                                    filter_out_dict=dict(func_id=[58941,16062]), #just excludes those
                                    
                                    #filter_equal_dict=dict(func_id=58941),
                                   offset=None #this is an integer that will set the offset
                                   )
df

,id,valid,pt_position,pt_supervoxel_id,pt_root_id,func_id
0,1,True,"[181147, 143788, 22167]",89660913577302088,864691135569117318,29020
1,2,True,"[182993, 135610, 21130]",89941288908184714,864691135517422218,61953
2,4,True,"[149711, 151738, 17565]",85369450370657325,864691135724333739,28753
3,6,True,"[174921, 137614, 21123]",88815663879226337,864691136084134252,66903
4,7,True,"[168410, 226141, 21120]",87912758674392495,864691136108768952,78672
5,8,True,"[167981, 216288, 21544]",87911453071334473,864691135278269857,31152
6,9,True,"[198007, 174819, 16975]",91987273352108825,864691135953898760,90886
7,10,True,"[182135, 178367, 20199]",89806255002300957,864691136116205476,52905
8,11,True,"[162796, 184639, 19827]",87133136009787684,864691135162313773,71347
9,12,True,"[164935, 177785, 21218]",87484017859149629,864691136951664863,57369
10,13,True,"[206577, 133261, 18640]",93177907207497424,864691135988449792,51325
11,14,True,"[168181, 161960, 21511]",87904100087286054,864691136023889209,64237
12,15,True,"[181861, 198619, 16754]",89809003311686584,864691136209072060,61377
13,16,True,"[204851, 143787, 19186]",92968244151133945,864691135564752471,58129
14,17,True,"[185043, 185343, 21265]",90229429674286157,864691135446675028,20361
15,18,True,"[181169, 181492, 21889]",89665998751768317,864691135510524112,30128
16,19,True,"[206811, 155433, 20512]",93180931132713432,864691136378815445,74385
17,20,True,"[177437, 213778, 19873]",89177746601127042,864691136105538521,81648
18,21,True,"[202346, 167997, 17807]",92619630044487968,864691137019596142,82106
19,22,True,"[152409, 226078, 19308]",85731327336693119,864691136903144370,93552
20,23,True,"[313386, 174566, 26220]",107890542024761410,864691136118489624,16106
21,24,True,"[306839, 213638, 24733]",106980970829413237,864691136227020113,16552
22,25,True,"[324817, 212116, 23986]",109443670583292717,864691135888577417,16692
23,26,True,"[290540, 135491, 26952]",104718725923906897,864691135440543560,28713
24,27,True,"[291803, 169742, 22256]",104864067013098853,864691135538173042,29947
25,28,True,"[299964, 170610, 26714]",105990036243235261,864691135367033849,30298
26,29,True,"[292172, 160290, 25727]",104933130556860850,864691135117980637,49028
27,30,True,"[294375, 160683, 23115]",105214673917454809,864691135660569584,51416
28,31,True,"[295774, 123171, 23440]",105420763628551975,864691135583884664,54240
29,32,True,"[311546, 157458, 22902]",107606798835887611,864691135718541617,55958
30,33,True,"[301816, 223456, 23649]",106278657642871284,864691135099901728,59706
31,34,True,"[297818, 159084, 24458]",105707049102838100,864691135385422677,61042
32,35,True,"[299067, 123129, 22993]",105913344770753749,864691134884807418,62347
33,36,True,"[287036, 125025, 23889]",104224701203002036,864691135272206865,64573
34,37,True,"[311594, 157500, 22902]",107606798835886805,864691135718541617,66103
35,38,True,"[275364, 160058, 23827]",102610961730745211,864691135748674857,68397
36,39,True,"[320911, 155330, 25498]",108873092969256720,864691135593659947,69823
37,40,True,"[317058, 156414, 24562]",108380717784334769,864691135700409211,70913
38,41,True,"[298779, 166548, 24632]",105848748730577131,864691136143561524,77983
39,42,True,"[322183, 176189, 22803]",109087016364643885,864691135012639734,79776
40,43,True,"[278320, 169248, 25240]",103034411347552977,864691136194298600,86363
41,44,True,"[289859, 175441, 25125]",104653717097226174,864691135850577863,86705
42,45,True,"[292612, 167390, 24276]",105004461172496411,864691135953895944,88728
43,46,True,"[303559, 143174, 21984]",106478974649547656,864691135776732256,91561
44,47,True,"[296712, 168512, 23849]",105567548497849354,864691136811995507,93986

In [40]:
# you can see how many annotations are in this table
client.materialize.get_annotation_count('synapses_pni_2')

HTTPError: 504 Server Error: Gateway Time-out for url: https://minnie.microns-daf.com/materialize/api/v2/datastack/minnie65_phase3_v1/version/3/table/synapses_pni_2/count content:b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.15.10</center>\r\n</body>\r\n</html>\r\n'

# Join Query Example

In [53]:
import datajoint_utils as du

In [54]:
minnie,schema = du.configure_minnie_vm()

INFO - 2020-11-25 01:55:09,756 - settings - Setting stores to {'minnie65': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65', 'stage': '/mnt/dj-stor01/platinum/minnie65'}, 'meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/meshes'}, 'decimated_meshes': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes', 'stage': '/mnt/dj-stor01/platinum/minnie65/02/decimated_meshes'}, 'skeletons': {'protocol': 'file', 'location': '/mnt/dj-stor01/platinum/minnie65/02/skeletons'}}
INFO - 2020-11-25 01:55:09,757 - settings - Setting enable_python_native_blobs to True
INFO - 2020-11-25 01:55:09,772 - connection - Connected celiib@at-database.ad.bcm.edu:3306
INFO - 2020-11-25 01:55:09,958 - settings - Setting enable_python_native_blobs to True

Connecting celiib@at-database.ad.bcm.edu:3306

In [55]:
minnie.SegToDecimateFromNuclei()

*segment_id
+------------+
86469113155952
86469113162540
86469113177147
86469113183427
86469113186830
86469113188179
86469113190613
86469113192730
86469113195336
86469113195623
86469113199341
86469113199384
   ...
 (Total: 114784)

In [60]:
df = client.materialize.query_table('synapses_pni_2',
                                    #filter_in_dict=dict(func_id=[58941,16062]),
                                    filter_in_dict=dict(pre_pt_root_id=[864691131771477291,864691131881790489]), #just excludes those
                                    
                                    #filter_equal_dict=dict(func_id=58941),
                                   offset=0 #this is an integer that will set the offset
                                   )
df

Empty DataFrame
Columns: [id, valid, pre_pt_position, pre_pt_supervoxel_id, pre_pt_root_id, ctr_pt_position, post_pt_position, post_pt_supervoxel_id, post_pt_root_id, size]
Index: []

In [57]:
df

,id,valid,pre_pt_position,pre_pt_supervoxel_id,pre_pt_root_id,ctr_pt_position,post_pt_position,post_pt_supervoxel_id,post_pt_root_id,size
0,6138400,True,"[78492, 121806, 20623]",75584209602941406,864691135756026049,"[78494, 121806, 20631]","[78526, 121708, 20637]",75584209602956077,864691135052953845,1000.0
1,6138402,True,"[78470, 119650, 20621]",75583934725022902,864691136807365860,"[78508, 119668, 20626]","[78582, 119716, 20623]",75583934725029799,864691132802447067,25448.0
2,6138404,True,"[78540, 120540, 20554]",75584072163916222,864691135053009909,"[78518, 120620, 20549]","[78540, 120560, 20542]",75584072163894809,864691134319861886,14960.0
3,6138405,True,"[78468, 119384, 20604]",75583866005532975,864691136825158884,"[78494, 119426, 20604]","[78510, 119418, 20599]",75583866005529753,864691134494121975,1088.0
4,6138406,True,"[78496, 119248, 20622]",75583866005553456,864691134493698807,"[78522, 119212, 20630]","[78464, 119188, 20628]",75583866005557854,864691135134701337,5072.0
...,...,...,...,...,...,...,...,...,...,...
199995,5745126,True,"[80020, 104440, 16618]",75792978836465984,864691134124653983,"[79992, 104482, 16620]","[79948, 104466, 16620]",75792978836464854,864691135656460179,3528.0
199996,5745130,True,"[80022, 102600, 16776]",75792772678168222,864691134561342246,"[80022, 102548, 16772]","[80008, 102538, 16763]",75792703958680910,864691135634863017,19636.0
199997,5745131,True,"[80094, 102074, 16863]",75792635239281607,864691135009268846,"[80051, 102047, 16863]","[80024, 102078, 16869]",75792635239295648,864691135924721080,25712.0
199998,5906638,True,"[80738, 114834, 18117]",75864722171444835,864691136374813806,"[80770, 114810, 18110]","[80802, 114858, 18116]",75864722171443121,864691134888729993,25432.0
199999,5906640,True,"[80724, 116206, 17975]",75864928329748533,864691132430132050,"[80698, 116204, 17976]","[80728, 116200, 17982]",75864928329754277,864691132430131794,3072.0

In [ ]:
2